name: Build

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Builds on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macOS-latest
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release