name: Clippy

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Runs "cargo clippy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Cache .cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-clippy-${{ hashFiles('**/Cargo.toml') }}

      - name: cargo clippy
        run: cargo clippy --all --all-features -- -D warnings