name: Format

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    name: Runs "cargo fmt"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Cache .cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-fmt-${{ hashFiles('**/Cargo.toml') }}

      - name: Run fmt
        run: cargo fmt --all -- --check